spring:
  jmx:
    enabled: true
  kafka:
    bootstrapServers: ${BOOTSTRAP_SERVERS:localhost:9092}
    security.protocol: ${SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      trust-store-location: file://${SSL_TRUST_STORE_LOCATION:/opt/kafka-streams-template/ssl/truststore.jks}
      trust-store-password: ${SSL_TRUST_STORE_PASSWORD}
      key-store-location: file://${KAFKA_GENETIC_TO_MTB_XML_SSL_KEY_STORE_LOCATION:/opt/kafka-streams-template/ssl/keystore.jks}
      key-store-password: ${KAFKA_GENETIC_TO_MTB_XML_SSL_KEY_STORE_PASSWORD}
  cloud:
    function:
      definition: process
    stream:
      bindings:
        process-in-0:
          destination: ${KAFKA_TOPIC_GEN_MH_GUIDE_INFO:mh-guide-gen-info}
        process-in-1:
          destination: ${KAFKA_TOPIC_MTB_PATIENT_INFO:mtb-patient-info}

      kafka:
        streams:
          binder:
            applicationId: kafka-genetic-to-mtb-xml
            configuration:
              #resetOffset: true
              compression.type: gzip
              max.request.size: 5242880
              startOffset: latest
services:
  mtbSender:
    #TODO http://127.0.0.1:5000/MTBFile:
    post_url: ${URL_MTB_POST:http://localhost:8080}
    mtb-username: ${MTB_USERNAME:test}
    mtb-password: ${MTB_PASSWORD:mypass}

metadata:
  ngsReports:
    kitManufacturer: ${KIT_MANUFACTURER:Archer}
    sequencer: ${SEQUENCER:Illumina NovaSeq 6000}
    referenceGenome: ${REFERENCE_GENOME:GRCh37}
    sequencingType: ${SEQUENCING_TYPE:PanelKit}
    sequencingTypeShort: ${SEQUENCING_TYPE_SHORT:Panel}
    interpolationSystem: ${INTERPOLATION_SYSTEM:MH Guide}
    reportedFocality: ${REPORTED_FOCALITY:complete}
    panel: ${PANEL:Archer Complete Solid Tumor}
    seqKitTypVP: ${SEQKITTYP_VP:Archer VariantPlex Complete Solid Tumor}
    seqPipelineVP: ${SEQPIPELINE_VP:urn:Marburg:VP:CST:1.0:MHGuide:6.3.0}
    seqKitTypVPCP: ${SEQKITTYP_VPCP:Archer VP Complete Solid Tumor + FP Pan Solid Tumor v2}
    seqPipelineVPCP: ${SEQPIPELINE_VPCP:urn:Marburg:VP:CST:1.0:FP:PST:1.0:MHGuide:6.3.0}
    fachabteilungKennung: ${FACHABTEILUNGKENNUNG:ITCCC}
    einrichtungKennung: ${EINRICHTUNGKENNUNG:CCCUMR}
    durchfuehrendeOE: ${DURCHFUEHRENDEOE:CCCUMR}
    durchfuehrendeOEKurzText: ${DURCHFUEHRENDEOE_KURZTEXT:CCC Marburg}
    internExternWert: ${INTERNEXTERN_WERT:M}
    internExternKurztext: ${INTERNEXTERN_KURZTEXT:Meine Einrichtung}
    analyseMethoden: ${ANALYSE_METHODE:S}

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "health, prometheus, info, metric"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.kafka.config: info
    de.unimarburg.diz.kafkagenetictomtbxml: debug
