spring:
  jmx:
    enabled: true
  kafka:
    bootstrapServers: ${BOOTSTRAP_SERVERS:localhost:9092}
    security.protocol: ${SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      trust-store-location: file://${SSL_TRUST_STORE_LOCATION:/opt/kafka-streams-template/ssl/truststore.jks}
      trust-store-password: ${SSL_TRUST_STORE_PASSWORD}
      key-store-location: file://${MTB_PID_TO_KAFKA_SSL_KEY_STORE_LOCATION:/opt/kafka-streams-template/ssl/keystore.jks}
      key-store-password: ${MTB_PID_TO_KAFKA_SSL_KEY_STORE_PASSWORD}
  cloud:
    function:
      definition: process
    stream:
      bindings:
        process-in-0:
          destination: ${KAFKA_TOPIC_GEN_MH_GUIDE_INFO:mh-guide-gen-info}
        process-in-1:
          destination: ${KAFKA_TOPIC_MTB_PID_INFO:mtb-pid-info}


      kafka:
        streams:
          binder:
            applicationId: kafka-genetic-to-mtb-xml
            configuration:
              #resetOffset: true
              compression.type: gzip
              max.request.size: 5242880
              startOffset: latest
services:
  mtbSender:
    post_url: ${URL_MTB_POST:http://127.0.0.1:5000/MTBFile}

metadata:
  ngsReports:
    kitManufacturer: ${KIT_MANUFACTURER:Archer}
    sequencer: ${SEQUENCER:Illumina NovaSeq 6000}
    referenceGenome: ${REFERENCE_GENOME:GRCh37}
    sequencingType: ${SEQUENCING_TYPE:Targeted NGS}
    interpolationSystem: ${INTERPOLATION_SYSTEM:MH Guide}
    reportedFocality: ${REPORTED_FOCALITY:complete}
    panel: ${PANEL:Archer Complete Solid Tumor}

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "health, prometheus, info, metric"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.kafka.config: info
    de.unimarburg.diz.kafkagenetictomtbxml: debug
